sample/sample/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sample.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ums/', include('ums.urls', namespace='ums')), 
)

sample/ums/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from ums import views

urlpatterns = patterns('',
	url(r'^user/edit/$', views.demouser_edit, name='demouser_edit'),
	url(r'^user/commit/(?P<demouser_id>\d+)/$', views.demouser_commit, name='demouser_commit'),
	url(r'^user/fin/(?P<demouser_id>\d+)/$', views.demouser_fin, name='demouser_fin'),
)

sample/ums/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _

class DemoUser(AbstractUser):
	"""DemoUser Model Class."""
	userfullname = models.CharField(u'お名前',blank=False,null=False,max_length=50)
	url = models.URLField(u'URL',blank=True,null=True)
	birth = models.DateField(u'生年月',blank=True,null=True)

	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = ['email', 'password']
	
	def __unicode__(self):
		return self.userfullname

	class Meta:
		db_table = 'user'
		swappable = 'AUTH_USER_MODEL'

sample/ums/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.extras import widgets
import datetime
from ums.models import DemoUser
from ums.widgets import MonthYearWidget

class DemoUserForm(forms.ModelForm):
	help_base=u'{0}文字以内で入力してください'
	username_len=30
	email_len=75
	password_len=128

	userfullname = forms.CharField(label=u'お名前',help_text=help_base.format(username_len),max_length=username_len)
	email = forms.EmailField(label=u'メールアドレス',help_text=u'有効なメールアドレスを'+help_base.format(email_len),max_length=email_len)
	password = forms.CharField(label=u'パスワード',help_text=help_base.format(password_len),widget=forms.PasswordInput(),max_length=password_len)
	password2 = forms.CharField(label=u'パスワード(再)',widget=forms.PasswordInput(),max_length=password_len)
	url = forms.URLField(label=u'URL',required=False)
	birth = forms.DateField(label=u'生年月',
		widget=MonthYearWidget(years=range(1900, datetime.datetime.today().year+1)),
		required=False)

	class Meta:
		model = DemoUser
		fields = ('userfullname','email','password','password2','url','birth')

	def clean_password2(self):
		password = self.cleaned_data.get('password')
		password2 = self.cleaned_data.get('password2')
		if password and password2:
			if password != password2:
				raise forms.ValidationError("パスワードが一致しません")
		return password2

sample/ums/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
from ums.forms import DemoUserForm
from ums.models import DemoUser

def demouser_edit(request):
	demouser = DemoUser()

	form = DemoUserForm(request.POST, instance=demouser)

	if form.is_valid():
		demouser = form.save(commit=True)
		demouser.save()
		return redirect('ums:demouser_commit',demouser.id)

	return render_to_response('ums/demouser_edit.html',dict(form=form),context_instance=RequestContext(request))

def demouser_commit(request, demouser_id):
	demouser = get_object_or_404(DemoUser, pk=demouser_id)

	if request.method == 'POST':
		form = DemoUserForm(request.POST, instance=demouser)
		if form.is_valid():
			demouser = form.save(commit=True)
			demouser.save()
			return redirect('ums:demouser_fin',demouser.id)
	else:
		form = DemoUserForm(instance=demouser)

	return render_to_response('ums/demouser_commit.html',dict(form=form,demouser_id=demouser_id),context_instance=RequestContext(request))

def demouser_fin(request, demouser_id):
	demouser = get_object_or_404(DemoUser, pk=demouser_id)
	return render_to_response('ums/demouser_fin.html',{'demouser': demouser},context_instance=RequestContext(request))

sample/ums/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}DemoUsers{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

sample/ums/templates/ums/demouser_commit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}登録内容確認{% endblock title %}

{% block content %}
    <h3 class="page-header">登録内容確認</h3>
    <p class="lead">登録内容を確認してください</p>
    <form action="{% url 'ums:demouser_commit' demouser_id=demouser_id %}" method="post" class="form-horizontal" role="form">
      {% csrf_token %}
      {{ form.userfullname|bootstrap_horizontal }}
      {{ form.email|bootstrap_horizontal }}
      {{ form.url|bootstrap_horizontal }}
      {{ form.birth|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">修正</button>
          <a href="{% url 'ums:demouser_fin' demouser_id=demouser_id %}" class="btn btn-primary">OK</a>
        </div>
      </div>
    </form>
{% endblock content %}

sample/ums/templates/ums/demouser_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}ご登録{% endblock title %}

{% block content %}
    <h3 class="page-header">ご登録</h3>
    <p class="lead">入力後、登録ボタンを押してください</p>
    <form action="{% url 'ums:demouser_edit' %}" method="post" class="form-horizontal" role="form">
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">登録</button>
        </div>
      </div>
    </form>
{% endblock content %}

sample/ums/templates/ums/demouser_fin.html
{% extends "base.html" %}
{% load bootstrap %}


{% block content %}
    <h3 class="page-header">登録完了しました</h3>
    <p class="lead">{{ demouser.userfullname }}さん、ご登録ありがとうございました</p>
      <div class="col-sm-offset-2 col-sm-10">
        <a href="{% url 'ums:demouser_edit' %}" class="btn btn-default btn-sm">戻る</a>
      </div>
{% endblock content %}